language: node_js
node_js:
  - lts/*
script: yarn build
before_install:
  - openssl aes-256-cbc -K $encrypted_b68f2d47b480_key -iv $encrypted_b68f2d47b480_iv -in id_tencent_cloud.enc -out ~\/.ssh/id_tencent_cloud -d
  - chmod 600 ~/.ssh/id_tencent_cloud
addons:
  ssh_known_hosts: 188.131.177.41
