# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Noah Personal Page CI

on:
  push:
    branches: [ source ]
  pull_request:
    branches: [ source ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2.1.3
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: cp nginx.conf dist/
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: master
          build_dir: dist
          keep_history: true
          fqdn: noahgao.net
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to ECS on Zhangjiakou
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd ~/projects/noah-page/ && git pull
          host: ${{ secrets.HOST_ECS_ZJK }}
          username: noah
          privateKey: ${{ secrets.PRIVATE_KEY_ECS_ZJK}}

