# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Noah Personal Page CI

on:
  push:
    branches: [ source ]
  pull_request:
    branches: [ source ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.3.0
        with:
          target_branch: master
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to OSS
        uses: fangbinwei/aliyun-oss-website-action@v1.2.2
        with:
            accessKeyId: ${{ secrets.OSS_AK }}
            accessKeySecret: ${{ secrets.OSS_SK }}
            bucket: noah-page
            endpoint: oss-cn-zhangjiakou.aliyuncs.com
            folder: dist
            skipSetting: false

